doctrine:
  dbal:
    url: 'sqlite:///%kernel.project_dir%/var/data.db'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: false
